"""empty message

Revision ID: 227ff7034e62
Revises: ceb9741a09a8
Create Date: 2026-01-30 02:54:54.864623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227ff7034e62'
down_revision = 'ceb9741a09a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Date(), nullable=True))
        batch_op.drop_column('time_stamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_stamp', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
