"""empty message

Revision ID: 4fc3c9fd5c1e
Revises: b016b1240b83
Create Date: 2026-01-20 20:23:22.981164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc3c9fd5c1e'
down_revision = 'b016b1240b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_log', schema=None) as batch_op:
        batch_op.alter_column('plant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_log', schema=None) as batch_op:
        batch_op.alter_column('plant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
