"""empty message

Revision ID: 722891bf9c1a
Revises: 4fc3c9fd5c1e
Create Date: 2026-01-22 02:29:54.795669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '722891bf9c1a'
down_revision = '4fc3c9fd5c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_stamp', sa.Date(), nullable=False),
    sa.Column('moisture_level', sa.Integer(), nullable=False),
    sa.Column('water', sa.Boolean(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('moisture_log', schema=None) as batch_op:
        batch_op.alter_column('time_stamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)

    with op.batch_alter_table('water_log', schema=None) as batch_op:
        batch_op.alter_column('time_stamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_log', schema=None) as batch_op:
        batch_op.alter_column('time_stamp',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('moisture_log', schema=None) as batch_op:
        batch_op.alter_column('time_stamp',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    op.drop_table('plant_status')
    # ### end Alembic commands ###
