"""empty message

Revision ID: d71a0253adba
Revises: 778900a39d0f
Create Date: 2026-02-01 16:33:25.304760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71a0253adba'
down_revision = '778900a39d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.alter_column('average_water_cycle',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.alter_column('average_water_cycle',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
